name: Create Notion diary page
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:
jobs:
  create-notion-diary-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: go get .
      - run: go build -v ./...
      - run: go-notion-diary-page-creator
        env:
          TZ: "Asia/Tokyo"
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_DIARY_DATABASE_ID: ${{ secrets.NOTION_DIARY_DATABASE_ID }}
